config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users



  # get "disable/:id" => "contacts#disable",as: :disable
  # get "enable/:id" => "contacts#enable",as: :enable

  get 'disable_contact/:id' => "contacts#disable_contact",as: :disable_contact
  get 'enable_contact/:id' => "contacts#enable_contact",as: :enable_contact

  get 'disable_region/:id' => "regions#disable_region",as: :disable_region
  get 'enable_region/:id' => "regions#enable_region",as: :enable_region

  get 'cities/index/:region_city_id/disable_city/:id' => "cities#disable_city",as: :disable_city
  get 'cities/index/:region_city_id/enable_city/:id' => "cities#enable_city",as: :enable_city

  get 'suburbs/index/:city_suburb_id/disable_suburb/:id' => "suburbs#disable_suburb",as: :disable_suburb
  get 'suburbs/index/:city_suburb_id/enable_suburb/:id' => "suburbs#enable_suburb",as: :enable_suburb

  get 'localities/index/:suburb_locality_id/disable_locality/:id' => "localities#disable_locality",as: :disable_locality
  get 'localities/index/:suburb_locality_id/enable_locality/:id' => "localities#enable_locality",as: :enable_locality


  get 'get_region' => "contacts#get_region"
  get 'get_city' => "contacts#get_city"
  get 'get_suburb' => "contacts#get_suburb"
  get 'update_city' => "suburbs#update_city"
  get 'update_suburb' => "localities#update_suburb"
  get 'update_city_loc' => "localities#update_city_loc"


  get 'cities/index/:region_city_id' => "cities#index", :as => "city_index"

  get 'suburbs/index/:city_suburb_id' => "suburbs#index", :as => "suburb_index"

  get 'localities/index/:suburb_locality_id' => "localities#index", :as => "locality_index"



  resources :localities
  resources :suburbs
  resources :cities
  resources :regions
  resources :contacts
  resources :users
  resources :permissions_roles
  resources :permissions
  resources :roles



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

app/models/locality.rb
class Locality < ApplicationRecord
  belongs_to :suburb,foreign_key: :suburb_id, class_name: "Suburb"

  validates :name, presence: {message: "Locality name cannot be blank"}
  validates :desc, presence: {message: "Description cannot be blank"}
end

app/controllers/localities_controller.rb
class LocalitiesController < ApplicationController
  before_action :set_locality, only: [:show, :edit, :update, :destroy, :disable_locality, :enable_locality]
  before_action :authenticate_user!
   load_and_authorize_resource
  before_action :load_permissions

  # GET /localities
  # GET /localities.json
  def index
    @localities = Locality.where(suburb_id: params[:suburb_locality_id]).order('name asc')
    @suburb = Suburb.find(params[:suburb_locality_id])
  end

  # GET /localities/1
  # GET /localities/1.json
  def show
  end

  # GET /localities/new
  def new
    @locality = Locality.new
    @city = City.all
    @region = Region.all
  end

  # GET /localities/1/edit
  def edit
    @city = City.all
    @region = Region.all
  end

  def update_city_loc
    reg_id = params["region_id"]
    @city_data = City.where(region_id: reg_id)

    @city_data = @city_data.map {|a| [a.name, a.id]}.insert(0, "")

    puts "----------------------------------"
    puts @city_data.inspect
    puts "----------------------------------"

  end

  def update_suburb

    city_id = params["city_id"]
    @suburb_data = Suburb.where(city_id: city_id)

    @suburb_data = @suburb_data.map {|a| [a.name, a.id]}.insert(0, "")

    puts "----------------------------------"
    puts "----------------------------------"
    puts @suburb_data.inspect
    puts "----------------------------------"
    puts "----------------------------------"
  end

  def disable_locality
    Locality.update(@locality.id, status: false)

    respond_to do |format|
      format.html {redirect_to locality_index_path(params[:suburb_locality_id]), notice: 'Locality was successfully disabled.'}
      format.json {head :no_content}
    end
  end

  def enable_locality
    Locality.update(@locality.id, status: true)

    respond_to do |format|
      format.html {redirect_to locality_index_path(params[:suburb_locality_id]), notice: 'Locality was successfully enabled.'}
      format.json {head :no_content}
    end
  end

  # POST /localities
  # POST /localities.json
  def create
    @locality = Locality.new(locality_params)

    params[:sub_id] = locality_params[:suburb_id]
    logger.info "This is suburb ID:: #{params[:sub_id].inspect}"
    respond_to do |format|
      if @locality.save
        format.html {redirect_to @locality, notice: 'Locality was successfully created.'}
        format.json {render :show, status: :created, location: @locality}
      else
        format.html {render :new}
        format.json {render json: @locality.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /localities/1
  # PATCH/PUT /localities/1.json
  def update
    respond_to do |format|
      params[:sub_id] = locality_params[:suburb_id]
      logger.info "This is suburb ID:: #{params[:sub_id].inspect}"
      if @locality.update(locality_params)
        format.html {redirect_to @locality, notice: 'Locality was successfully updated.'}
        format.json {render :show, status: :ok, location: @locality}
      else
        format.html {render :edit}
        format.json {render json: @locality.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /localities/1
  # DELETE /localities/1.json
  def destroy
    @locality.destroy
    respond_to do |format|
      format.html {redirect_to localities_url, notice: 'Locality was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_locality
    @locality = Locality.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def locality_params
    params.require(:locality).permit(:name, :desc, :status, :suburb_id)
  end
end

app/helpers/localities_helper.rb
module LocalitiesHelper
end

app/views/localities/_form.html.erb
<%= simple_form_for(@locality, :data => {sub_id: params[:sub_id]}) do |f| %>


  <div class="w3-container w3-card-4 w3-light-grey w3-text-blue w3-margin">
    <%#= f.input :suburb_id, collection: @region, label_method: :name, value_method: :id, label: "Region", input_html: {id: "region_link"} %>
    <%#= f.input :suburb_id, collection: @city, label_method: :name, value_method: :id, label: "City", input_html: {id: "suburb_link"} %>
    <%= f.input :suburb_id, label: "Suburb", as: :hidden, input_html: {id: "locality_link", value: params[:sub_id]} %>
    <%= f.input :name %>
    <%= f.input :desc %>
    <%= f.input :status, as: :hidden, input_html: {value: 1} %>

  </div>

  <div class="w3-container">
    <%= f.button :submit, class: 'w3-btn w3-blue w3-border w3-border-blue w3-round-large w3-hover-blue w3-hover-text-white w3-right' %>
    <%= link_to 'Back', locality_index_path(params[:sub_id]), class: 'w3-btn w3-black w3-border w3-border-black w3-round-large w3-hover-black w3-hover-text-white w3-left' %>
  </div>
<% end %>


<script type="text/javascript">

    $(document).ready(function () {
        $('#region_link').change(function () {
            $.ajax({
                url: "<%= update_city_loc_path %>",
                data: {
                    region_id: $('#region_link').val()
                },
                dataType: "script"
            });
        });
    });
    $('#suburb_link').change(function () {
        $.ajax({
            url: "<%= update_suburb_path %>",
            data: {
                city_id: $('#suburb_link').val()
            },
            dataType: "script"
        });
    });

</script>

app/views/localities/edit.html.erb
<div class="col-md-4"></div>
<div class="col-md-4 col-md-offset-4">
  <legend>Editing Locality</legend>

  <%= render 'form', locality: @locality %>
</div>
<div class="col-md-4"></div>

app/views/localities/index.html.erb
<div class="col-md-2"></div>
<div class="w3-container col-md-8 col-md-offset-2 w3-responsive">


  <legend>Localities</legend>

  <div class="w3-right">
    <h3><%= @suburb.name %></h3>
  </div>
  <table class="w3-container w3-card-4 w3-table table-bordered table-striped w3-table-all table-condensed">
    <thead>
    <tr class="w3-blue">
      <th>Name</th>
      <th>Desc</th>
      <th>Suburb</th>
      <th class="col-md-2" colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @localities.each do |locality| %>
      <tr>
        <td><%= locality.name %></td>
        <td><%= locality.desc %></td>
        <td><%= locality.suburb.name %></td>
        <td><%= link_to 'Show', locality, class: 'w3-btn w3-blue w3-border w3-border-blue w3-round w3-small w3-hover-blue w3-hover-text-white' %></td>
        <td><%= link_to 'Edit', edit_locality_path(locality, sub_id: params[:suburb_locality_id]), class: 'w3-btn w3-brown w3-text-white w3-border w3-border-brown w3-round w3-small w3-hover-brown w3-hover-text-white' %></td>
        <td>
          <% if locality.status %>
            <%= link_to disable_locality_path(locality.suburb.id, locality), class: 'w3-btn w3-red w3-border w3-border-red w3-round w3-small' do %>
              <i class="glyphicon glyphicon-ban-circle"></i>
            <% end %>
          <% elsif !locality.status %>
            <%= link_to enable_locality_path(locality.suburb.id, locality), class: 'w3-btn w3-green w3-border w3-border-green w3-round w3-small' do %>
              <i class="glyphicon glyphicon-ok"></i>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to suburb_index_path(city_suburb_id: @suburb.city_id), class: 'w3-btn w3-black w3-border w3-border-black w3-round w3-small w3-hover-black w3-hover-text-white' do %>
    <i class="glyphicon glyphicon-arrow-left"></i> Back
  <% end %>
  <%= link_to new_locality_path(sub_id: params[:suburb_locality_id]), class: 'w3-btn w3-green w3-border w3-border-green w3-round-large w3-hover-green w3-hover-text-white ' do %>
    <i class="glyphicon glyphicon-plus"></i>
  <% end %>
  <br>
  <br>
  <br>
</div>
<div class="col-md-2"></div>

app/views/localities/new.html.erb
<div class="col-md-4"></div>
<div class="col-md-4  col-md-offset-4">
<legend>New Locality</legend>

<%= render 'form', locality: @locality %>
</div>
<div class="col-md-4"></div>

app/views/localities/show.html.erb
<div class="col-md-4"></div>
<div class="w3-container col-md-4 col-md-offset-4">
  <div class="w3-container w3-card-4 w3-light-grey w3-text-blue w3-margin" style="padding-bottom: 6%; padding-top:2%;">
    <table class="w3-container w3-table table-bordered w3-table-all table-striped">
      <tr>
        <td class="w3-blue col-md-4"><strong>Name </strong></td>
        <td style="padding-left: 6%" class="w3-center"><%= @locality.name %></td>
      </tr>

      <tr>
        <td class="w3-blue col-md-4"><strong>Description </strong></td>
        <td style="padding-left: 6%" class="w3-center"><%= @locality.desc %></td>
      </tr>
      <tr>
        <td class="w3-blue col-md-4"><strong>Suburb</strong></td>
        <td style="padding-left: 6%" class="w3-center"><%= @locality.suburb.name %></td>
      </tr>
    </table>
  </div>
  <div class="w3-container">
    <%= link_to 'Back', locality_index_path(@locality.suburb_id), class: 'w3-btn w3-black w3-border w3-border-black w3-round-large w3-hover-black w3-hover-text-white w3-left', style: 'margin-right: 4px' %>
    <%= link_to 'Edit', edit_locality_path(@locality, sub_id: @locality.suburb.id), class: 'w3-btn w3-blue w3-border w3-border-blue w3-round-large w3-hover-blue w3-hover-text-white w3-left' %>
  </div>
</div>

app/views/localities/update_city_loc.js.erb
$("#suburb_link").html(
    "<%= escape_javascript(options_for_select(@city_data)) %>"
);

app/views/localities/update_suburb.js.erb
$("#locality_link").html(
    "<%= escape_javascript(options_for_select(@suburb_data)) %>"
);