config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users



  # get "disable/:id" => "contacts#disable",as: :disable
  # get "enable/:id" => "contacts#enable",as: :enable

  get 'disable_contact/:id' => "contacts#disable_contact",as: :disable_contact
  get 'enable_contact/:id' => "contacts#enable_contact",as: :enable_contact

  get 'disable_region/:id' => "regions#disable_region",as: :disable_region
  get 'enable_region/:id' => "regions#enable_region",as: :enable_region

  get 'cities/index/:region_city_id/disable_city/:id' => "cities#disable_city",as: :disable_city
  get 'cities/index/:region_city_id/enable_city/:id' => "cities#enable_city",as: :enable_city

  get 'suburbs/index/:city_suburb_id/disable_suburb/:id' => "suburbs#disable_suburb",as: :disable_suburb
  get 'suburbs/index/:city_suburb_id/enable_suburb/:id' => "suburbs#enable_suburb",as: :enable_suburb

  get 'localities/index/:suburb_locality_id/disable_locality/:id' => "localities#disable_locality",as: :disable_locality
  get 'localities/index/:suburb_locality_id/enable_locality/:id' => "localities#enable_locality",as: :enable_locality


  get 'get_region' => "contacts#get_region"
  get 'get_city' => "contacts#get_city"
  get 'get_suburb' => "contacts#get_suburb"
  get 'update_city' => "suburbs#update_city"
  get 'update_suburb' => "localities#update_suburb"
  get 'update_city_loc' => "localities#update_city_loc"


  get 'cities/index/:region_city_id' => "cities#index", :as => "city_index"

  get 'suburbs/index/:city_suburb_id' => "suburbs#index", :as => "suburb_index"

  get 'localities/index/:suburb_locality_id' => "localities#index", :as => "locality_index"



  resources :localities
  resources :suburbs
  resources :cities
  resources :regions
  resources :contacts
  resources :users
  resources :permissions_roles
  resources :permissions
  resources :roles



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

app/models/suburb.rb
class Suburb < ApplicationRecord
  belongs_to :city,foreign_key: :city_id, class_name: "City"

  has_many :localities, class_name: "Locality"

  validates :name, presence: {message: "Suburb name cannot be blank"}
  validates :desc, presence: {message: "Description cannot be blank"}
end

app/controllers/suburbs_controller.rb
class SuburbsController < ApplicationController
  before_action :set_suburb, only: [:show, :edit, :update, :destroy,:disable_suburb,:enable_suburb]
  before_action :authenticate_user!
   load_and_authorize_resource
  before_action :load_permissions

  # GET /suburbs
  # GET /suburbs.json
  def index
    @suburbs = Suburb.where(city_id: params[:city_suburb_id]).order('name asc')
    @city = City.find(params[:city_suburb_id])
  end

  # GET /suburbs/1
  # GET /suburbs/1.json
  def show
  end

  # GET /suburbs/new
  def new
    @suburb = Suburb.new
    @region = Region.all
  end

  # GET /suburbs/1/edit
  def edit
    @region = Region.all
  end

  def disable_suburb
    #params[:reg_id] = city_params[:region_city_id]
    Suburb.update(@suburb.id,status: false)
    respond_to do |format|
      format.html { redirect_to suburb_index_path(params[:city_suburb_id]), notice: 'Suburb was successfully disabled.' }
      format.json { head :no_content }
    end
  end

  def enable_suburb
    #params[:reg_id] = city_params[:region_city_id]
    Suburb.update(@suburb.id,status: true)
    respond_to do |format|
      format.html { redirect_to suburb_index_path(params[:city_suburb_id]), notice: 'Suburb was successfully enabled.' }
      format.json { head :no_content }
    end
  end

  # POST /suburbs
  # POST /suburbs.json
  def create
    @suburb = Suburb.new(suburb_params)
    params[:cit_id] = suburb_params[:city_id]
    logger.info "This is city ID:: #{params[:cit_id].inspect}"

    respond_to do |format|
      if @suburb.save
        format.html { redirect_to @suburb, notice: 'Suburb was successfully created.' }
        format.json { render :show, status: :created, location: @suburb }
      else
        format.html { render :new }
        format.json { render json: @suburb.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /suburbs/1
  # PATCH/PUT /suburbs/1.json
  def update
    respond_to do |format|
      params[:cit_id] = suburb_params[:city_id]
      logger.info "This is city ID:: #{params[:cit_id].inspect}"
      if @suburb.update(suburb_params)
        format.html { redirect_to @suburb, notice: 'Suburb was successfully updated.' }
        format.json { render :show, status: :ok, location: @suburb }
      else
        format.html { render :edit }
        format.json { render json: @suburb.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_city
    reg_id=params["region_id"]
    @city_data=City.where(region_id: reg_id)

    @city_data=@city_data.map{|a|[a.name,a.id]}.insert(0,"Please select from the option below")

    puts "----------------------------------"
    puts @city_data.inspect
    puts "----------------------------------"

  end

  # DELETE /suburbs/1
  # DELETE /suburbs/1.json
  def destroy
    @suburb.destroy
    respond_to do |format|
      format.html { redirect_to suburbs_url, notice: 'Suburb was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_suburb
      @suburb = Suburb.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def suburb_params
      params.require(:suburb).permit(:name, :desc, :status, :city_id)
    end
end

app/helpers/suburbs_helper.rb
module SuburbsHelper
end

app/views/suburbs/_form.html.erb
<%= simple_form_for(@suburb,:data =>{cit_id: params[:cit_id]}) do |f| %>
  <%#= f.error_notification %>

  <div class="w3-container w3-card-4 w3-light-grey w3-text-black w3-margin">
    <%= f.input :city_id,  as: :hidden, input_html: {id: "region_link",value: params[:cit_id]} %>
    <%= f.input :name %>
    <%= f.input :desc %>
    <%= f.input :city,label: "City", input_html: {id: "city_link",as: :hidden} %>
    <%= f.input :status, as: :hidden,input_html: {value: true} %>
  </div>

  <div class="w3-container">
    <%= f.button :submit,class: 'w3-btn w3-blue w3-border w3-border-blue w3-round-large w3-hover-blue w3-hover-text-white w3-right' %>
    <%= link_to 'Back', suburb_index_path(params[:cit_id]), class: 'w3-btn w3-black w3-border w3-border-black w3-round-large w3-hover-black w3-hover-text-white w3-left', style: 'margin-right: 4px' %>
  </div>
<% end %>


<!--getting the suburb based on region and city-->
<script type="text/javascript">
    $(document).ready(function () {
        $('#region_link').change(function () {
            $.ajax({
                url: "<%= update_city_path %>",
                data: {
                    region_id: $('#region_link').val()
                },
                dataType: "script"
            });
        });
    });
</script>

app/views/suburbs/edit.html.erb
<div class="col-md-4"></div>
<div class="col-md-4 col-md-offset-4">
<legend>Editing Suburb</legend>

<%= render 'form', suburb: @suburb %>
</div>
<div class="col-md-4"></div>

app/views/suburbs/index.html.erb
<div class="col-md-2"></div>
<div class="w3-container col-md-8 col-md-offset-2 w3-responsive">


  <legend>Suburbs</legend>


  <div class="w3-right">
    <h3><%= @city.name %></h3>
  </div>

  <table class="w3-table w3-card-4 w3-table-all table-striped table-bordered table-condensed">
    <thead>
    <tr class="w3-blue">
      <th class="col-md-2">Name</th>
      <th>Description</th>
      <th class="col-md-2">City</th>
      <th class="col-md-2" colspan="4"></th>
    </tr>
    </thead>

    <tbody>
    <% @suburbs.each do |suburb| %>
      <% loc_num = Locality.where(suburb_id: suburb.id).count %>
      <% logger.info "Locality number:: #{loc_num.inspect}" %>
      <tr>
        <td><%= suburb.name %></td>
        <td><%= suburb.desc %></td>
        <td><%= suburb.city.name %></td>
        <td><%= link_to 'Show', suburb, class: 'w3-btn w3-blue w3-border w3-border-blue w3-round w3-small w3-hover-blue w3-hover-text-white' %></td>
        <td><%= link_to 'Localities ('+loc_num.to_s+')', locality_index_path(suburb), class: 'w3-btn w3-teal w3-border w3-border-teal w3-round w3-small w3-hover-teal w3-hover-text-white' %></td>
        <td><%= link_to 'Edit', edit_suburb_path(suburb, cit_id: params[:city_suburb_id]), class: 'w3-btn w3-brown w3-text-white w3-border w3-border-brown w3-round w3-small w3-hover-brown w3-hover-text-white' %></td>
        <td>
          <% if suburb.status %>
            <%= link_to  disable_suburb_path(suburb.city.id, suburb), class: 'w3-btn w3-red w3-border w3-border-red w3-round w3-small' do%>
              <i class="glyphicon glyphicon-ban-circle"></i>
            <% end %>
          <% elsif !suburb.status %>
            <%= link_to  enable_suburb_path(suburb.city.id, suburb), class: 'w3-btn w3-green w3-border w3-border-green w3-round w3-small' do%>
              <i class="glyphicon glyphicon-ok"></i>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to city_index_path(region_city_id: @city.region_id), class: 'w3-btn w3-black w3-border w3-border-black w3-round w3-small w3-hover-black w3-hover-text-white' do %>
    <i class="glyphicon glyphicon-arrow-left"></i> Back
  <% end %>

  <%= link_to  new_suburb_path(cit_id: params[:city_suburb_id]), class: 'w3-btn w3-green w3-text-white w3-border w3-border-green w3-round w3-small w3-hover-green w3-hover-text-white' do %>
    <i class="glyphicon glyphicon-plus"></i>
  <% end %>
  <br>
  <br>
</div>
<div class="col-md-2"></div>

app/views/suburbs/new.html.erb
<div class="col-md-4"></div>
<div class="col-md-4 col-md-offset-4">
<legend>New Suburb</legend>

<%= render 'form', suburb: @suburb %>
</div>
<div class="col-md-4"></div>

app/views/suburbs/show.html.erb
<div class="col-md-4"></div>
<div class="w3-container col-md-4 col-md-offset-4">
  <div class="w3-container w3-card-4 w3-light-grey w3-text-blue w3-margin" style="padding-bottom: 6%; padding-top:2%;">

    <table class="w3-text-black w3-container w3-table table-bordered w3-table-all table-striped">
      <tr>
        <td class="w3-teal"><strong>Name </strong></td>
        <td style="padding-left: 6%"><%= @suburb.name %></td>
      </tr>

      <tr>
        <td class="w3-teal"><strong>Description </strong></td>
        <td style="padding-left: 6%"><%= @suburb.desc %></td>
      </tr>
      <tr>
        <td class="w3-teal"><strong>City</strong></td>
        <td style="padding-left: 6%"><%= @suburb.city.name %></td>
      </tr>
    </table>
  </div>
  <div class="w3-container">
    <%= link_to 'Back', suburb_index_path(@suburb.city_id), class: 'w3-btn w3-black w3-border w3-border-black w3-round-large w3-hover-black w3-hover-text-white w3-left', style: 'margin-right: 4px' %>
    <%= link_to 'Edit', edit_suburb_path(@suburb,cit_id: @suburb.city.id), class: 'w3-btn w3-blue w3-border w3-border-blue w3-round-large w3-hover-blue w3-hover-text-white w3-left' %>
  </div>
</div>

app/views/suburbs/update_city.js.erb
$("#city_link").html(
    "<%= escape_javascript(options_for_select(@city_data)) %>"
);