config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users



  # get "disable/:id" => "contacts#disable",as: :disable
  # get "enable/:id" => "contacts#enable",as: :enable

  get 'disable_contact/:id' => "contacts#disable_contact",as: :disable_contact
  get 'enable_contact/:id' => "contacts#enable_contact",as: :enable_contact

  get 'disable_region/:id' => "regions#disable_region",as: :disable_region
  get 'enable_region/:id' => "regions#enable_region",as: :enable_region

  get 'cities/index/:region_city_id/disable_city/:id' => "cities#disable_city",as: :disable_city
  get 'cities/index/:region_city_id/enable_city/:id' => "cities#enable_city",as: :enable_city

  get 'suburbs/index/:city_suburb_id/disable_suburb/:id' => "suburbs#disable_suburb",as: :disable_suburb
  get 'suburbs/index/:city_suburb_id/enable_suburb/:id' => "suburbs#enable_suburb",as: :enable_suburb

  get 'localities/index/:suburb_locality_id/disable_locality/:id' => "localities#disable_locality",as: :disable_locality
  get 'localities/index/:suburb_locality_id/enable_locality/:id' => "localities#enable_locality",as: :enable_locality


  get 'get_region' => "contacts#get_region"
  get 'get_city' => "contacts#get_city"
  get 'get_suburb' => "contacts#get_suburb"
  get 'update_city' => "suburbs#update_city"
  get 'update_suburb' => "localities#update_suburb"
  get 'update_city_loc' => "localities#update_city_loc"


  get 'cities/index/:region_city_id' => "cities#index", :as => "city_index"

  get 'suburbs/index/:city_suburb_id' => "suburbs#index", :as => "suburb_index"

  get 'localities/index/:suburb_locality_id' => "localities#index", :as => "locality_index"



  resources :localities
  resources :suburbs
  resources :cities
  resources :regions
  resources :contacts
  resources :users
  resources :permissions_roles
  resources :permissions
  resources :roles



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

app/models/region.rb
class Region < ApplicationRecord
  has_many :cities, class_name: "City"

  validates :name, presence: {message: "Region name cannot be blank"}
  validates :desc, presence: {message: "Description cannot be blank"}
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  before_action :set_region, only: [:show, :edit, :update, :destroy,:enable_region,:disable_region]
  before_action :authenticate_user!
   load_and_authorize_resource
  before_action :load_permissions

  # GET /regions
  # GET /regions.json
  def index
    @regions = Region.all.order('name asc')
    # @reg_count=City.group(:region_id).count
    #
    # puts @reg_count.inspect
  end

  # GET /regions/1
  # GET /regions/1.json
  def show
  end

  # GET /regions/new
  def new
    @region = Region.new
  end

  # GET /regions/1/edit
  def edit
  end

  def disable_region
    Region.update(@region.id,status: false)
    respond_to do |format|
      format.html { redirect_to regions_url, notice: 'Region was successfully disabled.' }
      format.json { head :no_content }
    end
  end

  def enable_region
    Region.update(@region.id,status: true)
    respond_to do |format|
      format.html { redirect_to regions_url, notice: 'Region was successfully enabled.' }
      format.json { head :no_content }
    end
  end

  # POST /regions
  # POST /regions.json
  def create
    @region = Region.new(region_params)

    respond_to do |format|
      if @region.save
        format.html { redirect_to @region, notice: 'Region was successfully created.' }
        format.json { render :show, status: :created, location: @region }
      else
        format.html { render :new }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /regions/1
  # PATCH/PUT /regions/1.json
  def update
    respond_to do |format|
      if @region.update(region_params)
        format.html { redirect_to @region, notice: 'Region was successfully updated.' }
        format.json { render :show, status: :ok, location: @region }
      else
        format.html { render :edit }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /regions/1
  # DELETE /regions/1.json
  def destroy
    @region.destroy
    respond_to do |format|
      format.html { redirect_to regions_url, notice: 'Region was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_region
      @region = Region.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def region_params
      params.require(:region).permit(:name, :desc, :status)
    end
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/views/regions/_form.html.erb
<%= simple_form_for(@region) do |f| %>
  <%#= f.error_notification %>

  <div class="w3-container w3-card-4 w3-light-grey w3-text-black w3-margin">
    <%= f.input :name %>
    <%= f.input :desc ,label: "Description"%>
    <%= f.input :status,as: :hidden ,input_html: {value: true}%>
  </div>

  <div class="w3-container">
    <%= f.button :submit, class: 'w3-btn w3-blue w3-border w3-border-blue w3-round-large w3-hover-blue w3-hover-text-white w3-right' %>
    <%= link_to 'Back', regions_path,class: 'w3-btn w3-black w3-border w3-border-black w3-round-large w3-hover-black w3-hover-text-white w3-left' %>
  </div>
<% end %>

app/views/regions/edit.html.erb
<div class="col-md-4"></div>
<div class="col-md-4 col-md-offset-4">
<legend>Editing Region</legend>

<%= render 'form', region: @region %>
</div>

app/views/regions/index.html.erb
<div class="col-md-2"></div>
<div class="w3-container col-md-8 col-md-offset-2 w3-responsive">


  <legend>Regions</legend>

  <table class="w3-table w3-card-4 table-bordered w3-table-all table-striped table-condensed">
    <thead>
    <tr class="w3-blue">
      <th class="col-md-2">Name</th>
      <th>Description</th>
      <th class="col-md-2" colspan="4"></th>
    </tr>
    </thead>

    <tbody>
    <% @regions.each do |region| %>
    <% city_num = City.where(region_id: region.id).count %>
      <% logger.info "City number:: #{city_num.inspect}" %>

      <tr>
        <td><%= region.name %></td>
        <td><%= region.desc %></td>
        <!--        Create a new route for cities and pass a parameter in it-->
        <td><%= link_to 'Show', region, class: 'w3-btn w3-blue w3-border w3-border-blue w3-round w3-small w3-hover-blue w3-hover-text-white' %></td>
        <td><%= link_to 'Cities ('+city_num.to_s+')', city_index_path(region), class: 'w3-btn w3-teal w3-border w3-border-teal w3-round w3-small w3-hover-teal w3-hover-text-white' %></td>
        <td><%= link_to 'Edit', edit_region_path(region), class: 'w3-btn w3-brown w3-text-white w3-border w3-border-brown w3-round w3-small w3-hover-brown w3-hover-text-white' %></td>

        <td>
          <% if region.status %>
            <%= link_to disable_region_path(region.id), data: { confirm: 'Are you sure?' },class: 'w3-btn w3-red w3-border w3-border-red w3-round w3-small' do %>
              <i class="glyphicon glyphicon-ban-circle"></i>
            <% end %>
          <% elsif !region.status %>
            <%= link_to enable_region_path(region.id), data: { confirm: 'Are you sure?' },class: 'w3-btn w3-green w3-border w3-border-green w3-round w3-small' do %>
              <i class="glyphicon glyphicon-ok"></i>
            <% end %>
          <% end %>
        </td>

      </tr>
    <% end %>
    </tbody>
  </table>

  <br>


  <%= link_to new_region_path, class: 'w3-btn w3-green w3-text-white w3-border w3-border-green w3-round w3-small w3-hover-green w3-hover-text-white' do %>
    <i class="glyphicon glyphicon-plus"></i>
  <% end %>
</div>
<div class="col-md-2"></div>

app/views/regions/new.html.erb
<div class="col-md-4"></div>
<div class="col-md-4 col-md-offset-4">
<legend>New Region</legend>
<%= render 'form', region: @region %>
</div>
<div class="col-md-4"></div>

app/views/regions/show.html.erb
<div class="col-md-4"></div>
<div class="w3-container col-md-4 col-md-offset-4">
  <div class="w3-container w3-card-4 w3-light-grey w3-text-blue w3-margin" style="padding-bottom: 6%; padding-top:2%;">

    <table class="w3-container w3-table table-bordered w3-table-all table-striped">
      <tr>
        <td class="w3-teal"><strong>Name </strong></td>
        <td style="padding-left: 6%"class="w3-text-black"><%= @region.name %></td>
      </tr>

      <tr>
        <td class="w3-teal"><strong>Description </strong></td>
        <td style="padding-left: 6%" class="w3-text-black"><%= @region.desc %></td>
      </tr>
    </table>
  </div>
  <div class="w3-container">
    <%= link_to 'Back', regions_path, class: 'w3-btn w3-black w3-border w3-border-black w3-round-large w3-hover-black w3-hover-text-white w3-left', style: 'margin-right: 4px' %>
    <%= link_to 'Edit', edit_region_path(@region), class: 'w3-btn w3-blue w3-border w3-border-blue w3-round-large w3-hover-blue w3-hover-text-white w3-left' %>
  </div>
</div>