config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users



  # get "disable/:id" => "contacts#disable",as: :disable
  # get "enable/:id" => "contacts#enable",as: :enable

  get 'disable_contact/:id' => "contacts#disable_contact",as: :disable_contact
  get 'enable_contact/:id' => "contacts#enable_contact",as: :enable_contact

  get 'disable_region/:id' => "regions#disable_region",as: :disable_region
  get 'enable_region/:id' => "regions#enable_region",as: :enable_region

  get 'cities/index/:region_city_id/disable_city/:id' => "cities#disable_city",as: :disable_city
  get 'cities/index/:region_city_id/enable_city/:id' => "cities#enable_city",as: :enable_city

  get 'suburbs/index/:city_suburb_id/disable_suburb/:id' => "suburbs#disable_suburb",as: :disable_suburb
  get 'suburbs/index/:city_suburb_id/enable_suburb/:id' => "suburbs#enable_suburb",as: :enable_suburb

  get 'localities/index/:suburb_locality_id/disable_locality/:id' => "localities#disable_locality",as: :disable_locality
  get 'localities/index/:suburb_locality_id/enable_locality/:id' => "localities#enable_locality",as: :enable_locality


  get 'get_region' => "contacts#get_region"
  get 'get_city' => "contacts#get_city"
  get 'get_suburb' => "contacts#get_suburb"
  get 'update_city' => "suburbs#update_city"
  get 'update_suburb' => "localities#update_suburb"
  get 'update_city_loc' => "localities#update_city_loc"


  get 'cities/index/:region_city_id' => "cities#index", :as => "city_index"

  get 'suburbs/index/:city_suburb_id' => "suburbs#index", :as => "suburb_index"

  get 'localities/index/:suburb_locality_id' => "localities#index", :as => "locality_index"



  resources :localities
  resources :suburbs
  resources :cities
  resources :regions
  resources :contacts
  resources :users
  resources :permissions_roles
  resources :permissions
  resources :roles



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

app/models/ability.rb
class Ability

  include CanCan::Ability

  def initialize(user)
    user.role.permissions.each do |permission|
      if permission.subject_class == "all"
        can permission.action.to_sym, permission.subject_class.to_sym
      else
        can permission.action.to_sym, permission.subject_class.constantize
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :region,foreign_key: :region_id, class_name: "Region"

  # belongs_to :contact,foreign_key: :region_id, class_name: "Contact"

  has_many :suburbs, class_name: "Suburb"

  validates :name, presence: {message: "City name cannot be blank"}
  validates :desc, presence: {message: "Description cannot be blank"}
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user, foreign_key: :user_id, class_name: "User"

  belongs_to :locality, foreign_key: :locality_id, class_name: "Locality"

  validates :phone_number, presence: {message: "Phone Number cannot be blank"}, length: {minimum: 10, maximum: 10},uniqueness: true
  validates :surname, presence: {message: "Surname cannot be blank"}
  validates :othernames, presence: {message: "Othername(s) cannot be blank"}

  def self.firstname_search(firstname)
    firstname = "%#{firstname}%"
    where('surname LIKE ?', firstname)
  end

  def self.phone_number_search(phone_number)
    phone_number = "%#{phone_number}%"
    where('phone_number LIKE ?', phone_number)
  end


  def surname=(value)
    super value.titleize
  end

  def self.mysearch
    where(id: 1)
  end
end

app/models/locality.rb
class Locality < ApplicationRecord
  belongs_to :suburb,foreign_key: :suburb_id, class_name: "Suburb"

  validates :name, presence: {message: "Locality name cannot be blank"}
  validates :desc, presence: {message: "Description cannot be blank"}
end

app/models/permission.rb
class Permission < ApplicationRecord
end

app/models/permissions_role.rb
class PermissionsRole < ApplicationRecord
end

app/models/region.rb
class Region < ApplicationRecord
  has_many :cities, class_name: "City"

  validates :name, presence: {message: "Region name cannot be blank"}
  validates :desc, presence: {message: "Description cannot be blank"}
end

app/models/role.rb
class Role < ApplicationRecord
  # attr_accessible :name

  has_many :users
  has_and_belongs_to_many :permissions

  validates :name, presence: true, uniqueness: true

  def set_permissions(permissions)
    permissions.each do |id|
      permission = Permission.find(id)
      self.permissions << permission
      case permission.subject_class
      when "Part"
        case permission.action
        when "create"
          self.permissions << Permission.where(subject_class: "Drawing", action: "create")
        when "update"
          self.permissions << Permission.where(subject_class: "Drawing", action: ["update", "destroy"])
        end
      end
    end
  end
end

app/models/suburb.rb
class Suburb < ApplicationRecord
  belongs_to :city,foreign_key: :city_id, class_name: "City"

  has_many :localities, class_name: "Locality"

  validates :name, presence: {message: "Suburb name cannot be blank"}
  validates :desc, presence: {message: "Description cannot be blank"}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name,presence: true
  validates :email,presence: true
  belongs_to :role,class_name: "Role",foreign_key: :role_id

  def super_admin?
    self.role.name=="Super Admin"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/localities_helper.rb
module LocalitiesHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/suburbs_helper.rb
module SuburbsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<div class="col-md-4"></div>
<div class="col-md-4">
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>
</div>

app/views/layouts/_navi_emp_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse w3-blue w3-border-blue">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar w3-white"></span>
        <span class="icon-bar w3-white"></span>
        <span class="icon-bar w3-white"></span>
      </button>
      <% if user_signed_in? %>


      <%= link_to 'Phonebook', root_path, class: 'navbar-brand w3-text-white' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav w3-text-white navbar-right ">


        <%= render 'layouts/navigation_links' %>

        <% else %>
          <%= render 'layouts/navi_emp_links' %>
        <% end %>


      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>



<li class="w3-hover-white">
  <%= link_to contacts_path, class: "w3-hover-text-blue w3-text-white" do %>
    <i class="glyphicon glyphicon-phone-alt"></i> Contact
  <% end %>

</li>

<li class=" w3-hover-white dropdown">

  <a href="#" class="dropdown-toggle w3-text-white w3-hover-text-blue" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
    <span class="glyphicon glyphicon-wrench"></span> Setup</a>
  <ul class="dropdown-menu">
    <!--    <li><a href="#">Action</a></li>-->
    <!--    <li><a href="#">Another action</a></li>-->
    <!--    <li><a href="#">Something else here</a></li>-->
    <!--    <li role="separator" class="divider"></li>-->

    <li class="w3-hover-white">
      <%= link_to regions_path, class: "w3-hover-text-blue" do %>
        <i class="glyphicon glyphicon-globe"></i> Region
      <% end %>

      <%= link_to roles_path, class: "w3-hover-text-blue" do %>
        <i class="glyphicon glyphicon-globe"></i> Role
      <% end %>

      <%= link_to permissions_path, class: "w3-hover-text-blue" do %>
        <i class="glyphicon glyphicon-globe"></i> Permission
      <% end %>

      <%= link_to permissions_roles_path, class: "w3-hover-text-blue" do %>
        <i class="glyphicon glyphicon-globe"></i> Manage Permissions
      <% end %>
    </li>
  </ul>
</li>

<!--<li class="w3-hover-white dropdown">-->

<!--  <a href="#" class="dropdown-toggle w3-text-white w3-hover-text-blue" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Setup-->
<!--    <span class="caret"></span></a>-->

<!--  <ul class="w3-white dropdown-menu">-->

<!--      <li class="w3-hover-white">-->
<%#= link_to 'Region', regions_path, class: "w3-text-black" %>
<!--      </li>-->
<!--      <li role="separator" class="divider"></li>-->
<!--      <li class="w3-hover-white">-->
<%#= link_to 'City', cities_path, class: "w3-text-black" %>
<!--      </li>-->
<!--      <li role="separator" class="divider"></li>-->
<!--      <li class=" w3-hover-white">-->
<%#= link_to 'Suburb', suburbs_path, class: "w3-text-black" %>
<!--      </li>-->
<!--      <li role="separator" class="divider"></li>-->
<!--      <li class=" w3-hover-white">-->
<%#= link_to 'Locality', localities_path, class: "w3-text-black" %>
<!--      </li>-->

<!--  </ul>-->
<!--</li>-->

<li class=" w3-hover-white dropdown">

  <a href="#" class="dropdown-toggle w3-text-white w3-hover-text-blue" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
    <span class="glyphicon glyphicon-user"></span> <%= current_user.name.titleize %></a>
  <ul class="dropdown-menu">
    <!--    <li><a href="#">Action</a></li>-->
    <!--    <li><a href="#">Another action</a></li>-->
    <!--    <li><a href="#">Something else here</a></li>-->
    <!--    <li role="separator" class="divider"></li>-->
    <li>  <%= link_to 'Edit Profile', edit_user_registration_path, class: "w3-text-blue" %></li>
    <li>  <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "w3-text-blue" %></li>
  </ul>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Phonebook" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Phonebook" %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
      <script>
          $("#menu-toggle").click(function(e) {
              e.preventDefault();
              $("#wrapper").toggleClass("toggled");
          });
      </script>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>